config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :accounts
  resources :transactions
  
  resources :sessions, only: [:new, :create, :destroy] do
    get :password_combination, on: :collection
    post :verify_combination, on: :collection
    get 'validate_characters', on: :collection
    post 'validate_characters', on: :collection
    get :enter_characters, on: :collection
  end

  get '/logout', to: 'sessions#destroy', as: :logout

  get 'transactions/show', to: 'transactions#show', as: 'transactions_show'

  resources :password_combinations, only: [:show]

  post '/csp_report', to: 'csp_reports#report'
end

app/models/user.rb
class User < ApplicationRecord
    attr_encrypted :selected_characters, key: Figaro.env.secret_key
    attr_encrypted :identity_document, key: Figaro.env.secret_key
    attr_encrypted :card_number, key: Figaro.env.secret_key

    has_many :senders
    has_many :receivers
  
    has_secure_password
    has_many :accounts
    has_many :sent_transactions, class_name: 'Transaction', foreign_key: 'sender_id'
    has_many :received_transactions, class_name: 'Transaction', foreign_key: 'receiver_id'
    has_one :selected_characters_combination, class_name: 'PasswordCombination'
    has_many :password_combinations
  
    validates :username, presence: true, length: { maximum: 50 }
    validates :mail, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
    validates :password, length: { minimum: 8 }, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#\$%\^&\*])/, message: "must include lowercase, uppercase, digit and special character and should not be the same as username or email" }, exclusion: { in: ->(user) { [user.username, user.mail] }, message: "must include lowercase, uppercase, digit and special character and should not be the same as username or email" }
    validates :identity_document, presence: true, format: { with: /\A[A-Za-z]{3}\d{6}\z/ }
    validates :card_number, presence: true, uniqueness: true
  
    after_create :generate_and_save_password_combinations
    after_create :create_user_account

    def authenticate_with_selected_characters(selected_characters)
        stored_combination = password_combinations.sample
        stored_combination.authenticate(selected_characters)
    end
  
    def generate_and_save_password_combinations
      selected_characters = generate_random_selected_characters
      combination_data = {
        combination: selected_characters.join(''),
        character_positions: selected_characters_positions(selected_characters)
      }
  
      self.password_combinations.create(combination_data)
    end
  
    private
  
    def generate_random_selected_characters
      password.chars.sample(rand(3..6))
    end
  
    def selected_characters_positions(selected_characters)
      selected_characters.map { |char| password.index(char) + 1 }
    end

    def create_user_account
      account = Account.new(user: self)
      account.generate_account_number
      account.save
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:create, :new]

  def index
  end

  def show
    @user = User.find(session[:user_id])
    if User.find(session[:user_id]) != User.find(params[:id])
      session[:user_id] = nil
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.card_number = SecureRandom.hex(8).upcase
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(session[:user_id])
    
    if @user&.authenticate(user_params[:current_password]) && user_params[:password] == user_params[:password_confirmation]
      Rails.logger.info('Current password is valid.')
      if @user.update(password: user_params[:password])
        @user.generate_and_save_password_combinations
        redirect_to transactions_path, notice: 'Password and selected_characters updated successfully.'
      else
        flash.now[:alert] = "Error: #{user.errors.full_messages.join(', ')}"
        render :edit
      end
    else
      flash.now[:alert] = 'Invalid current password or passwords do not match.'
      render :edit
    end
  end    

  private

  /def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end/

  def set_user
    @user = User.find(session[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :card_number, :mail, :identity_document, :password_confirmation, :current_password)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in.'
      redirect_to root_path
    end
  end

  def require_login
    redirect_to root_path unless logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <head>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.email_field :mail %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "new-password", id: 'password-field' %>
  </div>
  
  <div id="password-strength-container" style="display: none;">
    <p>Password Strength: <span id="password-strength"></span></p>
  </div>

  <div class="field">
    <%= form.label :identity_document %>
    <%= form.text_field :identity_document %>
  </div>

  <div class="actions">
    <%= form.submit "Register" %>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      $('#password-field').on('input', function() {
        var password = $(this).val();
        var strength = calculatePasswordStrength(password);
        $('#password-strength').text(strength);
        $('#password-strength-container').show();
      });

      function calculatePasswordStrength(password) {
        let score = 0;

        if (password.length >= 8) score += 2;

        if (/[a-z]/.test(password) && /[A-Z]/.test(password)) score += 2;
        if (/\d/.test(password)) score += 2;
        if (/[!@#\$%\^&\*]/.test(password)) score += 2;

        const entropy = calculateShannonEntropy(password);
        const entropyScore = Math.min(2, entropy / 4.0);
        score += Math.round(entropyScore * 2);

        const strength = Math.round((score / 10.0) * 10);
        return `${strength}/10`;
      }

      function calculateShannonEntropy(input) {
        const uniqueCharacters = new Set(input);
        const inputLength = input.length;
        let entropy = 0;

        uniqueCharacters.forEach(char => {
          const frequency = input.split(char).length - 1;
          const probability = frequency / inputLength;
          entropy -= probability * Math.log2(probability);
        });

        return entropy;
      }
    });
  </script>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= h(user.username) %>
  </p>

  <p>
    <strong>Card number:</strong>
    <%= h(user.card_number) %>
  </p>

  <p>
    <strong>Identity document:</strong>
    <%= h(user.identity_document) %>
  </p>
</div>

app/views/users/edit.html.erb
<h1>Edit Password</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
  <head>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this password from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :current_password %>
  <%= form.password_field :current_password %>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, id: "password-field" %>  
  </div>

  <div id="password-strength-container" style="display: none;">
    <p>Password Strength: <span id="password-strength"></span></p>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit "Change Password" %>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      $('#password-field').on('input', function() {
        var password = $(this).val();
        var strength = calculatePasswordStrength(password);
        $('#password-strength').text(strength);
        $('#password-strength-container').show();
      });

      function calculatePasswordStrength(password) {
        let score = 0;

        if (password.length >= 8) score += 2;

        if (/[a-z]/.test(password) && /[A-Z]/.test(password)) score += 2;
        if (/\d/.test(password)) score += 2;
        if (/[!@#\$%\^&\*]/.test(password)) score += 2;

        const entropy = calculateShannonEntropy(password);
        const entropyScore = Math.min(2, entropy / 4.0);
        score += Math.round(entropyScore * 2);

        const strength = Math.round((score / 10.0) * 10);
        return `${strength}/10`;
      }

      function calculateShannonEntropy(input) {
        const uniqueCharacters = new Set(input);
        const inputLength = input.length;
        let entropy = 0;

        uniqueCharacters.forEach(char => {
          const frequency = input.split(char).length - 1;
          const probability = frequency / inputLength;
          entropy -= probability * Math.log2(probability);
        });

        return entropy;
      }
    });
  </script>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New client</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back", 'http://127.0.0.1:3000' %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Home", 'http://127.0.0.1:3000' %>
</div>