config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :accounts
  resources :transactions
  
  resources :sessions, only: [:new, :create, :destroy] do
    get :password_combination, on: :collection
    post :verify_combination, on: :collection
    get 'validate_characters', on: :collection
    post 'validate_characters', on: :collection
    get :enter_characters, on: :collection
  end

  get '/logout', to: 'sessions#destroy', as: :logout

  get 'transactions/show', to: 'transactions#show', as: 'transactions_show'

  resources :password_combinations, only: [:show]

  post '/csp_report', to: 'csp_reports#report'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    helper_method :current_user, :logged_in?

    before_action :require_login
    before_action :set_transaction, only: %i[show edit update destroy]
  
    def index
      transaction_account_balance
      @transactions = Transaction.where(sender_id: current_user.accounts.pluck(:id))
                                 .or(Transaction.where(receiver_id: current_user.accounts.pluck(:id)))
    end 
  
    def show
      @transaction = Transaction.find(params[:id])
  
      unless current_user.accounts.exists?(@transaction.sender_id) || current_user.accounts.exists?(@transaction.receiver_id)
        flash[:error] = "You are not authorized to view this transaction."
        redirect_to transactions_path
      end
    end
  
  
    def new
      @transaction = Transaction.new
    end
  
    def create
      @transaction = Transaction.new(transaction_params)
    
      sender_account = current_user.accounts.first
      @transaction.sender = sender_account
    
      recipient_account_number = params[:transaction][:recipient_account_number]
      recipient = Account.find_by(account_number: recipient_account_number)
    
      if recipient
        @transaction.receiver = recipient
      else
        flash.now[:alert] = 'Recipient account not found.'
        render :new and return
      end

      amount = params[:transaction][:amount].to_f

      if amount <= 0 || amount.to_s != params[:transaction][:amount] || amount.to_s.split(".")[1].to_s.length > 2
        flash.now[:alert] = 'Invalid amount.'
        render :new and return
      end

      if amount > sender_account.balance
        flash.now[:alert] = 'Insufficient funds.'
        render :new and return
      end

      sender_account.balance -= params[:transaction][:amount].to_f
      recipient.balance += params[:transaction][:amount].to_f

      ActiveRecord::Base.transaction do
        sender_account.save!
        recipient.save!
        @transaction.save!
      end
    
      if @transaction.save
        redirect_to transactions_path, notice: 'Transaction was successfully created.'
      else
        render :new
      end

      rescue ActiveRecord::RecordInvalid => e
        flash.now[:alert] = e.record.errors.full_messages.join(', ')
        render :new
    end        
  
    def edit
    end
  
    def update
      /if @transaction.update(transaction_params)
        redirect_to @transaction, notice: 'Transaction was successfully updated.'
      else
        render :edit
      end/
    end

    def transaction_account_balance
      sender_account = current_user.accounts.first
      @balance = sender_account.balance
    end
      
    def destroy
      /@transaction.destroy
      redirect_to transactions_url/
    end
  
    private
  
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
  
    def transaction_params
      params.require(:transaction).permit(:amount, :title, :recipient_name, :recipient_account_number)
    end    

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to root_path
      end
    end
  end
  

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :recipient_name, style: "display: block" %>
    <%= form.text_field :recipient_name %>
  </div>

  <div>
    <%= form.label :recipient_account_number, style: "display: block" %>
    <%= form.text_field :recipient_account_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Amount:</strong>
    <%= h(transaction.amount) %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= h(transaction.title) %>
  </p>

  <p>
    <strong>Sender name:</strong>
    <%= h(transaction.sender.user.username) %>
  </p>

  <p>
    <strong>Recipient name:</strong>
    <%= h(transaction.recipient_name) %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <header>
    <nav>
      <% if logged_in? %>
        <%= link_to "Profile", current_user %>
        <%= link_to "Log out", logout_path, method: :delete %>
      <% end %>
    </nav>
  </header>

  <p>Balance: <%= @balance %></p>

  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

<%= link_to "Change password", edit_user_path(current_user) %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>